COLUMNS:
  CreditScore: float64
  Gender: int64
  Age: float64
  Tenure: float64
  Balance: float64
  NumOfProducts: float64
  HasCrCard: float64
  IsActiveMember: float64
  EstimatedSalary: float64
  Exited: int64
  Geography_Germany: int64
  Geography_Spain: int64

TARGET_COLUMN:
  name: Exited
